### PR TITLE
Make scopes settable

### PR DESCRIPTION
**Pull request by joecohens**
I still think it's a good idea to make scopes settable in case we need to modify them without need of dependency update. What do you think?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Not sure I like this. I did remove this on purpose. The idea being I don't care if people want to configure the scopes.

**Comment by joecohens** [comment]
Oh this is not for people to change it, if we need another scope like private repos or whatever you'll have to update the version of the package instead of just setting it.

**Comment by GrahamCampbell** [comment]
Yeh. I couldn't work out how we actually set that scope though when I tried to implement it. When we're hitting github, we have to set the scopes, but we don't know if the user wants private repos until github's responded to us. Any ideas?

**Comment by GrahamCampbell** [comment]
The solution will be having StyleCI and "StyleCI Pro" on different subdomains and they will be totally seperate websites. NB, this will not be launching for a good few months yet.

**Pull request closed without merging**
